ipicrun15x15mesh scripts now support "-d datadir"

diff --git a/scripts/ipicrun15x15meshinp b/scripts/ipicrun15x15meshinp
--- a/scripts/ipicrun15x15meshinp
+++ b/scripts/ipicrun15x15meshinp
@@ -6,17 +6,38 @@ function usage()
   echo "
     $ME: prepare to run ipic3d for supplied parameters
   
-    usage: $ME <XLEN> <YLEN>
+    usage: $ME [-d <outputdir>] <XLEN> <YLEN>
     
       <XLEN>: number of processors in X direction
       <YLEN>: number of processors in Y direction
+      <outputdir>: data by default
   "
 }
+
+  DATA=data
+  while getopts ":d:" opt
+  do
+    case $opt in
+      d)
+         DATA="$OPTARG"
+         ;;
+      \?)
+         echo "Invalid option: -$OPTARG" >&2
+	 exit 1
+         ;;
+      :)
+         echo "Option -$OPTARG requires an argument." >&2
+	 exit 1
+         ;;
+    esac
+  done
+  shift $(($OPTIND - 1))
 
 if [ $# -lt 2 ]; then usage; exit 1; fi
 
   : Parallel mode needs data to be empty ; \
-  rm -rf data/* ; \
+  rm -rf "$DATA"/* ; \
+  mkdir -p "$DATA"
 
   XLEN=$1 ; \
   YLEN=$2 ; \
@@ -39,9 +60,12 @@ if [ $# -lt 2 ]; then usage; exit 1; fi
   echo dt=$dt ; \
   : edit GEM.inp with modified parameters ; \
   sed " \
-    s/^dt *=.*/dt = $dt/ ; \
-    s/^XLEN *=.*/XLEN = $1/ ; \
-    s/^YLEN *=.*/YLEN = $2/ ; \
-    s/^nxc *=.*/nxc = $((15*$1))/ ; \
-    s/^nyc *=.*/nyc = $((15*$2))/ ;" parameters.inp > data/parameters.inp ; \
+    s@^dt *=.*@dt = $dt@ ; \
+    s@^XLEN *=.*@XLEN = $1@ ; \
+    s@^YLEN *=.*@YLEN = $2@ ; \
+    s@^nxc *=.*@nxc = $((15*$1))@ ; \
+    s@^nyc *=.*@nyc = $((15*$2))@ ; \
+    s@^SaveDirName *=.*@SaveDirName = $DATA@ ; \
+    s@^RestartDirName *=.*@RestartDirName = $DATA@ ; \
+    " parameters.inp > $DATA/parameters.inp
 
